'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),L=require('./agent-town-lessons.js'),C=require('./agent-town-campaign-engine.js'),First=require('./agent-town-engine.js');
assert.equal(L.lessons.length,59);assert.deepEqual(L.lessons.map(l=>l.id),Array.from({length:59},(_,i)=>i+2));
let scenarios=0,mutations=0;
for(const l of L.lessons){assert(l.title&&l.goal&&l.terms&&l.character&&l.kind);assert(l.fields.length>0);assert.equal(l.region,l.id<=20?0:l.id<=40?1:l.id<=52?2:3);for(let seed=0;seed<4;seed++){const result=L.run(l.id,l.solution,seed);assert(result.pass,`${l.id}/${seed}: ${JSON.stringify(result.checks)}`);assert(result.events.length&&result.checks.length);assert.notDeepEqual(l.scene(0),l.scene(2));scenarios++;}assert(![0,1,2,3].every(seed=>L.run(l.id,L.defaults(l.id),seed).pass),'default passes '+l.id);let detected=0;for(const f of l.fields){const c=structuredClone(l.solution);c[f.key]=structuredClone(f.value);if(JSON.stringify(c)===JSON.stringify(l.solution))continue;const failures=[0,1,2,3].filter(seed=>!L.run(l.id,c,seed).pass);if(failures.length){detected++;mutations++;}}assert(detected,'no detected key mutation '+l.id);}
const old={...First.initial(),rewardGranted:true,complete:true,observed:true,entered:true,certified:true,config:{tool:'weather',city:'request',missing:'ask',timeout:'stop'}};
let s=C.restore(null,First.restore(JSON.stringify(old)));assert(s.completed[1]);assert(C.unlocked(s,2));assert(!C.unlocked(s,3));assert.equal(C.restore(null,null).completed[1],undefined);
let rewards=1;
for(let id=2;id<=60;id++){assert(C.unlocked(s,id));s.current=id;s=C.configure(s,id,L.get(id).solution);assert.throws(()=>C.accept(s,id,false));s=C.update(s,id,{prediction:'根据输入与规则推测结果',observed:true});let result=C.accept(s,id,false);assert(result.passed);s=result.state;assert.throws(()=>C.accept(s,id,true));result=C.accept(s,id,true,undefined,'新输入改变数值，但规则不依赖固定答案');assert(result.passed);s=result.state;rewards++;assert.equal(Object.keys(s.completed).length,rewards);const repeated=C.accept(s,id,true,undefined,'重复测试');assert.equal(Object.keys(repeated.state.completed).length,rewards);s=C.restore(JSON.stringify(s),old);assert(s.completed[id]);}
assert.equal(Object.keys(s.completed).length,60);
const completed=structuredClone(s.completed);let replay=C.replay(s,32);assert.deepEqual(replay.completed,completed);assert.equal(C.record(replay,32).certified,false);assert(C.record(replay,32).attempts.length>=2);
let practice=C.initial();practice.mode='practice';practice.current=48;practice=C.configure(practice,48,L.get(48).solution);practice=C.update(practice,48,{prediction:'高相关资料放前',observed:true,assisted:true});practice=C.accept(practice,48,false).state;practice=C.accept(practice,48,true,undefined,'相关度变化后仍按同一原则排序').state;assert.equal(Object.keys(practice.completed).length,0);
let invalid=C.configure(s,60,L.defaults(60));assert.equal(C.record(invalid,60).certified,false);assert.throws(()=>C.accept(invalid,60,true,undefined,'changed'));assert.throws(()=>C.restore('broken'));assert.throws(()=>C.restore(JSON.stringify({...s,version:999})));assert.throws(()=>C.restore(JSON.stringify({...s,current:61})));let tampered=structuredClone(s);tampered.records[2].config.allow=false;assert.throws(()=>C.restore(JSON.stringify(tampered)));
// UI assets reference all models and keep the course/first-lesson files in place.
const html=fs.readFileSync(__dirname+'/agent-town.html','utf8');assert(html.includes('agent-town.js'));assert(html.includes('agent-town-campaign.js'));assert(html.includes('agent-town-lessons.js'));const controller=fs.readFileSync(__dirname+'/agent-town-campaign.js','utf8');assert(!/setItem\(['"](?:quiz-state|agent-learning-v2|agent-town-v1)['"]/.test(controller));assert(controller.includes('prefers')===false); // motion policy lives in CSS
assert(fs.readFileSync(__dirname+'/agent-town-campaign.css','utf8').includes('prefers-reduced-motion'));
console.log(`PASS: 60 lesson coverage (1 legacy + 59), ${scenarios} reference scenarios, ${mutations} key mutation detections; full unlock chain, one-time rewards, replay, v1 import, v2 reload, corrupt/tampered protection, practice isolation.`);
