const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),L=require('./agent-town-lessons.js'),C=require('./agent-town-campaign-engine.js'),E=require('./agent-town-engine.js');
function boot(seed={},quota=false){const store={...seed},nodes={};function el(id){return nodes[id]??={id,style:{},dataset:{},value:'',textContent:'',hidden:false,innerHTML:'',classList:{toggle(){},remove(){},add(){}},append(){},prepend(){},before(){},after(){},replaceChildren(){},setAttribute(){},removeAttribute(){},scrollIntoView(){},focus(){}};}
const ctx={TownLessons:L,TownCampaign:C,TownEngine:E,URLSearchParams,location:{search:''},structuredClone,Date,console,window:{addEventListener(){}},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{if(quota)throw Error('quota');store[k]=v;}},document:{getElementById:el,querySelector:el,querySelectorAll:()=>[],createElement:tag=>({...el('tag-'+tag),style:{},dataset:{}})}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/agent-town-campaign.js','utf8'),ctx);return {store,nodes,ctx};}
const oldKeys={'quiz-state':'keep quiz','agent-learning-v2':'keep evidence','agent-town-v1':JSON.stringify(E.initial())};let test=boot(oldKeys);assert.equal(test.store['quiz-state'],oldKeys['quiz-state']);assert.equal(test.store['agent-learning-v2'],oldKeys['agent-learning-v2']);assert.equal(test.store['agent-town-v1'],oldKeys['agent-town-v1']);assert(JSON.parse(test.store[C.KEY]).version===2);
const broken=boot({...oldKeys,[C.KEY]:'broken'});assert.equal(broken.store[C.KEY],'broken');assert(broken.nodes.campaignNotice.textContent.includes('未覆盖'));
const full=boot(oldKeys,true);assert.equal(full.store[C.KEY],undefined);assert(full.nodes.campaignNotice.textContent.includes('保存失败'));
const saved=JSON.parse(test.store[C.KEY]);test.store[C.KEY]=JSON.stringify({...saved,revision:saved.revision+1});test.nodes.campaignMode.value='practice';test.nodes.campaignMode.onchange();assert(test.nodes.campaignNotice.textContent.includes('另一页面'));assert.equal(JSON.parse(test.store[C.KEY]).revision,saved.revision+1);
const numericState=C.initial();numericState.current=50;numericState.mode='practice';const numeric=boot({...oldKeys,[C.KEY]:JSON.stringify(numericState)});numeric.ctx.document.getElementById('cfg-outer').value='1';numeric.ctx.document.getElementById('cfg-inner').value='2';numeric.nodes.prediction.value='一乘二等于二';numeric.nodes.explanation.value='';numeric.nodes.experimentRun.onclick();while(!numeric.nodes.eventNext.hidden)numeric.nodes.eventNext.onclick();numeric.nodes.localAccept.onclick();const after=JSON.parse(numeric.store[C.KEY]).records[50];assert.equal(after.config.outer,1);assert.equal(after.config.inner,2);assert(after.last.results.every(r=>r.pass));numeric.nodes['cfg-outer'].value='4';numeric.nodes.localAccept.onclick();assert(numeric.nodes.campaignNotice.textContent.includes('先写下预测并走完'));
console.log('PASS: real controller preserves course/v1 keys, corrupt save protected, quota failure remains visible, concurrent revision is not overwritten.');
